version: "3"
services:
  doc:
    build: ${DCI_GIT_REPO_DIR}/dci-doc
    ports:
      - "4000:80"
    healthcheck:
      test: curl -sf http://localhost
      interval: 15s
      timeout: 5s
      retries: 5
