version: '2'
services:
  registry:
    image: docker:stable-dind
    command: --insecure-registry=docker-registry.engineering.redhat.com
    privileged: true
    stdin_open: true
    tty: true
  feeder:
    build: ${DCI_GIT_REPO_DIR}/dci-feeder-api
    ports:
      - "5003:5003"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api:/opt/dci-feeder-api
    depends_on:
      - api
      - registry
    environment:
      - LOG_DIR=/tmp
      - CACHE_DIR=/var/cache
      - FLASK_DEBUG=1
      - DCI_LOGIN=admin
      - DCI_PASSWORD=admin
      - DCI_CS_URL=http://api:5000/
      - DOCKER_HOST=registry:2375
      - DCIFEEDERAPI_PORT=5003
      - DCIFEEDERAPI_HOST=0.0.0.0
    stdin_open: true
    tty: true
