version: "3"
services:
  ui:
    build:
      context: ${DCI_GIT_REPO_DIR}/dci-ui
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_HOST: ${DCI_CS_URL_EXTERNAL}
        VITE_SSO_URL: ${SSO_URL}
        VITE_SSO_REALM: ${SSO_REALM}
        VITE_SSO_CLIENT_ID: ${SSO_CLIENT_ID}
        VITE_SSO_SCOPE: ${SSO_AUDIENCES}
    depends_on:
      - api
    healthcheck:
      test: curl -sf http://localhost
      interval: 15s
      timeout: 5s
      retries: 5
