version: "3"
services:
  ansible:
    build: ${DCI_GIT_REPO_DIR}/dci-ansible
    depends_on:
      - api
    environment:
      - DCI_LOGIN=admin
      - DCI_PASSWORD=admin
      - DCI_CS_URL=http://api:5000/
      - DB_HOST=db
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient:Z
      - ${DCI_GIT_REPO_DIR}/dci-ansible:/opt/dci-ansible:Z
