version: '2'
services:
  keycloak:
    build: ${DCI_GIT_REPO_DIR}/dci-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8180"
  es:
    build: ${DCI_GIT_REPO_DIR}/dci-es
    ports:
      - "9200:9200"
      - "9300:9300"
  client:
    build: ${DCI_GIT_REPO_DIR}/python-dciclient
    depends_on:
      - api
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  doc:
    build: ${DCI_GIT_REPO_DIR}/dci-doc
    ports:
      - "4000:4000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-doc:/opt/dci-doc
      - /opt/dci-doc/node_modules