version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/redhat-external-realm.json
    volumes:
      - ./dci-keycloak/redhat-external-realm.json:/tmp/redhat-external-realm.json:Z
    ports:
      - "8180:8080"
    healthcheck:
      test: curl -sf http://keycloak:8080/auth
      interval: 15s
      timeout: 5s
      retries: 5
    command: -Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0
