version: "3"
volumes:
  feeder_worker_logs:
services:
  docker_auth:
    image: docker.io/cesanta/docker_auth:1
    command: /config/docker_auth_config.yml
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api/dci-docker-auth/config:/config:z
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api/dci-docker-auth/logs:/logs:Z
  docker_registry:
    image: docker.io/registry:2
    environment:
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://registry:2375/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=Docker registry
      - REGISTRY_AUTH_TOKEN_ISSUER=DCI auth server
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.crt
      - REGISTRY_HEALTH_STORAGEDRIVER_ENABLED=false
      - REGISTRY_HTTP_ADDR=0.0.0.0:5010
      - REGISTRY_HTTP_HOST=http://registry:2375/
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=${AWS_ACCESS_KEY_ID}
      - REGISTRY_STORAGE_S3_SECRETKEY=${AWS_SECRET_ACCESS_KEY}
      - REGISTRY_STORAGE_S3_REGION=us-east-1
      - REGISTRY_STORAGE_S3_BUCKET=${STORE_CONTAINER_BUCKET}
      - REGISTRY_STORAGE_S3_REGIONENDPOINT=http://minio:9000/
      - REGISTRY_STORAGE_S3_V4AUTH=true
      - REGISTRY_STORAGE_S3_SECURE=false
      - REGISTRY_STORAGE_S3_SKIPVERIFY=true
    ports:
      - "5010:5010"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api/dci-docker-auth/config/ssl:/ssl:z
    depends_on:
      minio:
        condition: service_healthy
    restart: on-failure
  registry:
    image: docker.io/centos/httpd
    ports:
      - "2375:2375"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api/dci-registry/httpd:/etc/httpd/conf.d:ro,Z
    depends_on:
      - docker_registry
      - docker_auth
  redis:
    image: quay.io/sclorg/redis-6-c8s
  podman_worker:
    build:
      context: ${DCI_GIT_REPO_DIR}/dci-feeder-api
      dockerfile: Dockerfile-podman
    env_file: ${DCI_GIT_REPO_DIR}/.env
    command: rq worker --url redis://redis/ --path /opt/dci-feeder-api/ --results-ttl 86400 dcifeeder_podman
    privileged: true
    security_opt:
      - label=disable
      - seccomp=unconfined
    devices:
      - /dev/fuse:rw
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api:/opt/dci-feeder-api:z,ro
      - feeder_worker_logs:/var/log/dci-feeder-api/jobs
  feeder_worker:
    image: localhost/dci-dev-env_feeder:latest
    env_file: ${DCI_GIT_REPO_DIR}/.env
    command: rq worker --url redis://redis/ --path /opt/dci-feeder-api/ --results-ttl 86400 dcifeeder dcifeeder_quick
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api:/opt/dci-feeder-api:z,ro
      - feeder_worker_logs:/var/log/dci-feeder-api/jobs
    deploy:
      mode: replicated
      replicas: 2
  feeder:
    build: ${DCI_GIT_REPO_DIR}/dci-feeder-api
    ports:
      - "5003:5003"
    command: gunicorn wsgi:application --access-logfile - --error-logfile - --log-level debug --timeout 0 --bind 0.0.0.0:5003 --reload
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-feeder-api:/opt/dci-feeder-api:z
      - feeder_worker_logs:/var/log/dci-feeder-api/jobs
    env_file: ${DCI_GIT_REPO_DIR}/.env
    depends_on:
      - api
      - registry
      - minio
      - redis
      - feeder_worker
      - podman_worker
