version: '2.1'
services:
  api:
    depends_on:
      swift:
        condition: service_healthy
    environment:
      - STORE_ENGINE=swift
      - STORE_HOST=swift
  swift:
    build: dci-swift
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "5001:5001"
    healthcheck:
      test: curl -sI http://swift:8081
      interval: 15s
      timeout: 5s
      retries: 5
