version: '2'
services:
  db:
    build: dci-db
    ports:
      - "5432:5432"
  api:
    build: ${DCI_GIT_REPO_DIR}/dci-control-server
    depends_on:
      - db
      - swift
      - keycloak
    environment:
      - DEBUG=1
      - API_HOST=api
      - DB_HOST=db
      - SWIFT_HOST=swift
      - SWIFT_PORT=8080
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server
    restart: always
  tox:
    build: dci-tox
    depends_on:
      - db
    environment:
      - DB_PORT=tcp://db:5432
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci/
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/dci-client/
      - ./settings:/tmp/settings
  ui:
    build: ${DCI_GIT_REPO_DIR}/dci-ui
    depends_on:
      - api
    ports:
      - "8000:8000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-ui:/opt/dci-ui
      - /opt/dci-ui/node_modules
  client:
    build: ${DCI_GIT_REPO_DIR}/python-dciclient
    depends_on:
      - api
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  swift:
    build: dci-swift
    command: /sbin/init
    privileged: true
    ports:
      - "5001:5000"
      - "8080:8080"
      - "35357:35357"
    stdin_open: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  keycloak:
    build: dci-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8180"
