version: '2'
services:
  db:
    build: ${DCI_GIT_REPO_DIR}/dci-db
    ports:
      - "5432:5432"
  api:
    build: ${DCI_GIT_REPO_DIR}/dci-control-server
    depends_on:
      - db
      - swift
    environment:
      - DB_HOST=db
      - SWIFT_HOST=swift
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server
  ui:
    build: ${DCI_GIT_REPO_DIR}/dci-ui
    depends_on:
      - api
    ports:
      - "8000:8000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-ui:/opt/dci-ui
      - /opt/dci-ui/node_modules
  swift:
    build: ${DCI_GIT_REPO_DIR}/dci-swift
    command: /sbin/init
    privileged: true
    ports:
      - "5001:5000"
      - "8080:8080"
      - "35357:35357"
    stdin_open: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

