version: '2'
services:
  db:
    image: centos/postgresql-94-centos7
    environment:
      - POSTGRESQL_USER=dci
      - POSTGRESQL_PASSWORD=dci
      - POSTGRESQL_DATABASE=dci
    ports:
      - "5432:5432"
  api:
    build: ${DCI_GIT_REPO_DIR}/dci-control-server
    depends_on:
      - db
      - swift
      - keycloak
    environment:
      - DEBUG=1
      - API_HOST=api
      - DB_HOST=db
      - STORE_HOST=swift
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server
    restart: always
  ui:
    build: ${DCI_GIT_REPO_DIR}/dci-ui
    depends_on:
      - api
    ports:
      - "8000:8000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-ui:/opt/dci-ui
      - /opt/dci-ui/node_modules
  client:
    build: ${DCI_GIT_REPO_DIR}/python-dciclient
    depends_on:
      - api
    environment:
      - DB_HOST=db
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server
  ansible:
    build: ${DCI_GIT_REPO_DIR}/dci-ansible
    depends_on:
      - api
    environment:
      - DCI_LOGIN=admin
      - DCI_PASSWORD=admin
      - DCI_CS_URL=http://api:5000/
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient
      - ${DCI_GIT_REPO_DIR}/dci-ansible:/opt/dci-ansible
  swift:
    build: dci-swift
    command: /sbin/init
    privileged: true
    ports:
      - "5001:5000"
      - "8080:8080"
      - "35357:35357"
    stdin_open: true
    tty: true
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8080"
