version: '2.1'
services:
  db:
    image: centos/postgresql-96-centos7
    environment:
      - POSTGRESQL_USER=dci
      - POSTGRESQL_PASSWORD=dci
      - POSTGRESQL_DATABASE=dci
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-db:/opt/app-root/src
    ports:
      - "5432:5432"
    healthcheck:
      test: source /opt/rh/rh-postgresql96/enable && pg_isready -d dci -U dci -h db
      interval: 15s
      timeout: 5s
      retries: 5
  api:
    build: ${DCI_GIT_REPO_DIR}/dci-control-server
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - DEBUG=1
      - API_HOST=api
      - DB_HOST=db
      - STORE_ENGINE=file
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server:Z
    restart: always
    healthcheck:
      test: curl -sf http://api:5000/api/v1
      interval: 15s
      timeout: 5s
      retries: 5
  ui:
    build: ${DCI_GIT_REPO_DIR}/dci-ui
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-ui:/opt/dci-ui:Z
      - /opt/dci-ui/node_modules
  client:
    build: ${DCI_GIT_REPO_DIR}/python-dciclient
    depends_on:
      api:
        condition: service_started
    environment:
      - DB_HOST=db
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient:Z
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server:Z
  ansible:
    build: ${DCI_GIT_REPO_DIR}/dci-ansible
    depends_on:
      api:
        condition: service_started
    environment:
      - DCI_LOGIN=admin
      - DCI_PASSWORD=admin
      - DCI_CS_URL=http://api:5000/
      - DB_HOST=db
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient:Z
      - ${DCI_GIT_REPO_DIR}/dci-ansible:/opt/dci-ansible:Z
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8080"
    healthcheck:
      test: curl -sf http://keycloak:8080/auth
      interval: 15s
      timeout: 5s
      retries: 5
