version: "3"
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  db:
    image: docker.io/centos/postgresql-96-centos7
    environment:
      - POSTGRESQL_USER=dci
      - POSTGRESQL_PASSWORD=dci
      - POSTGRESQL_DATABASE=dci
    volumes:
      - ./dci-db:/opt/app-root/src:Z
    ports:
      - "5432:5432"
    healthcheck:
      test: source /opt/rh/rh-postgresql96/enable && pg_isready -d dci -U dci -h db
      interval: 15s
      timeout: 5s
      retries: 5
  api:
    build: ${DCI_GIT_REPO_DIR}/dci-control-server
    depends_on:
      - db
      - minio
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server:z
    restart: always
    healthcheck:
      test: curl -sf http://api:5000/api/v1
      interval: 15s
      timeout: 5s
      retries: 5
  client:
    build: ${DCI_GIT_REPO_DIR}/python-dciclient
    depends_on:
      - api
    env_file: .env
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient:z
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server:z
