version: '2'
services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-DB
    ports:
      - "5432:5432"
  es:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-ES
    ports:
      - "9200:9200"
      - "9300:9300"
  api:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-API
    depends_on:
      - db
      - es
      - worker
      - swift
      - keycloak
    environment:
      - DB_PORT=tcp://db:5432
      - ES_PORT=tcp://es:9200
      - WORKER_PORT=tcp://worker:5557
      - SWIFT_PORT=tcp://swift:8000
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server
      - ./settings:/tmp/settings
  tox:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-TOX
    depends_on:
      - db
      - es
    environment:
      - DB_PORT=tcp://db:5432
      - ES_PORT=tcp://es:9200
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci/
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/dci-client/
      - ./settings:/tmp/settings
  app:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-APP
    depends_on:
      - api
    environment:
      - DISPLAY
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-ui:/opt/dci-ui
      - /tmp/.X11-unix:/tmp/.X11-unix
  client:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-CLIENT
    depends_on:
      - api
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  worker:
    build:
      context: .
      dockerfile: dockerfiles/${OSVer}/Dockerfile-WORKER
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  swift:
    build:
      context: .
      dockerfile: dockerfiles/services/Dockerfile-SWIFT
    command: /sbin/init
    privileged: true
    ports:
      - "5001:5000"
      - "8080:8080"
      - "35357:35357"
    stdin_open: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  keycloak:
    build:
      context: .
      dockerfile: dockerfiles/services/Dockerfile-KEYCLOAK
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8180"
