# DCI DOC
#
# VERSION               0.0.1


FROM fedora:23

RUN dnf update -y && dnf install -y make python-pip && dnf clean all

WORKDIR /opt/dci-doc

ADD dci-doc/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

# By default build the html version of the docs.
ENTRYPOINT "make" "html"
