# DCI DOC
#
# VERSION               0.0.1


FROM fedora:23

RUN dnf update -y && dnf install -y make python-pip && dnf clean all

WORKDIR /opt/dci-doc

COPY dci-doc/requirements.txt .
RUN pip install -r requirements.txt

ENTRYPOINT ["make"]
