# DCI DB
#
# VERSION               0.0.1


FROM fedora

RUN dnf update -y
RUN dnf install -y gcc libpqxx-devel libffi-devel python-devel \
    python-tox git python3-devel redhat-rpm-config

RUN easy_install -U pip
RUN easy_install-3.4 -U pip

ENV LANG "en_US.UTF-8"
ENV DISABLE_DB_START 1
ENV DISABLE_ES_START 1

ENV TOX_TESTENV_PASSENV "DB_PORT ES_PORT"
ENV DCI_SETTINGS_FILE /tmp/settings/settings_test.py

WORKDIR /opt
