FROM fedora:26

LABEL name="DCI APP" version="0.0.2"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN echo -e "[google-chrome]\n\
name=google-chrome - x86_64\n\
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64\n\
enabled=1\n\
gpgcheck=1\n\
showdupesfromrepos=1\n\
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub\n" > \
    /etc/yum.repos.d/google-chrome.repo

RUN dnf install -y nodejs npm google-chrome-stable liberation-mono-fonts && \
    dnf clean all

RUN mkdir -p /opt/dci-ui
WORKDIR /opt/dci-ui

EXPOSE 8000

CMD ["bash", "-c", "npm install && npm run dev"]
