FROM fedora:26

LABEL name="DCI ES" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
RUN echo -e "[elasticsearch-2.x]\n\
name=Elasticsearch repository for 2.x packages\n\
baseurl=http://packages.elastic.co/elasticsearch/2.x/centos\n\
gpgcheck=1\n\
gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch\n\
enabled=1" > /etc/yum.repos.d/elasticsearch.repo
RUN dnf install -y elasticsearch java-1.8.0-openjdk hostname && \
    dnf clean all

RUN echo "network.host: 0.0.0.0" >> /etc/elasticsearch/elasticsearch.yml

EXPOSE 9200 9300

CMD ["sh", "-c", "/usr/libexec/elasticsearch"]
