FROM fedora:26

LABEL name="DCI TOX" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN dnf install -y gcc libpqxx-devel libffi-devel openssl-devel \
    python-devel git python3-devel redhat-rpm-config \
    python-lxml libxslt-devel python-pip python3-setuptools python3-pip && \
    dnf clean all
RUN pip install tox

ENV LANG "en_US.UTF-8"
ENV DISABLE_DB_START 1
ENV DISABLE_ES_START 1
ENV DISABLE_INFLUXDB_START 1

ENV TOX_TESTENV_PASSENV "DB_PORT ES_PORT"
ENV DCI_SETTINGS_FILE /tmp/settings/settings_test.py

WORKDIR /opt

COPY entrypoints/tox.sh /entrypoint-tox.sh
ENTRYPOINT ["/entrypoint-tox.sh"]

CMD ["/bin/bash"]
