# DCI APP
#
# VERSION               0.0.1


FROM fedora:25

RUN echo -e "[google-chrome]\n" \
    "\rname=google-chrome - x86_64\n" \
    "\rbaseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64\n" \
    "\renabled=1\n" \
    "\rgpgcheck=1\n" \
    "\rshowdupesfromrepos=1\n" \
    "\rgpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub\n" > \
    /etc/yum.repos.d/google-chrome.repo


RUN dnf update -y
RUN dnf install -y nodejs npm tar bzip2 make freetype fontconfig unzip\
    google-chrome-stable libexif git

WORKDIR /tmp
RUN curl -O http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip
RUN cp chromedriver /usr/local/bin
RUN dbus-uuidgen > /var/lib/dbus/machine-id

RUN mkdir -p /opt/dci-ui
WORKDIR /opt/dci-ui

ADD dci-ui/package.json /opt/dci-ui/
RUN npm install -g gulp &&\
    npm install &&\
    npm cache clean

EXPOSE 8000 35729

CMD ["gulp", "serve:dev"]
