FROM fedora:25

LABEL name="DCI WORKER" version="0.0.2"
MAINTAINER DCI Team <distributed-ci@redhat.com>

ENV container docker

RUN dnf -y --setopt=tsflags=nodocs install \
    https://repos.fedorapeople.org/repos/openstack/openstack-ocata/rdo-release-ocata-2.noarch.rpm \
    https://packages.distributed-ci.io/dci-release.fc25.noarch.rpm && \
    dnf -y --setopt=tsflags=nodocs install postfix dci-api openssh-server \
    python-dciclient cronie && \
    dnf clean all

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

RUN echo "* * * * * DCI_LOGIN=admin DCI_PASSWORD=admin DCI_CS_URL=http://api:5000 /opt/dci-control-server/bin/dci-esindex > /dev/null" > /var/spool/cron/root
RUN echo -e "ES_HOST='es'\nES_PORT=9200" > /etc/dci-api/settings.py

RUN echo root:root | chpasswd && ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -N ''

RUN systemctl enable sshd postfix dci-worker crond

EXPOSE 22 5557

CMD ["/usr/sbin/init"]
