# DCI SWIFT
#
# VERSION               0.0.1


FROM centos:centos7

ENV container docker

RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs openssh-server
RUN yum -y update; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]


RUN yum -y install openssh-server; yum clean all; systemctl enable sshd.service
RUN echo root:root | chpasswd && ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -N ''


RUN yum install -y https://www.rdoproject.org/repos/rdo-release.rpm && \
    yum update -y && \
    yum install -y openstack-swift && \
    yum install -y openstack-swift-proxy openstack-swift-object && \
    yum install -y  openstack-swift-container openstack-swift-account && \
    yum install -y openstack-keystone mariadb-server && \

EXPOSE 6000 6001 6002

CMD ["/sbin/init"]
