FROM centos:7

LABEL name="DCI DOC" version="0.0.2"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN yum -y --setopt=tsflags=nodocs install epel-release \
    https://packages.distributed-ci.io/dci-release.el7.noarch.rpm \
    https://repos.fedorapeople.org/repos/openstack/openstack-mitaka/rdo-release-mitaka-6.noarch.rpm && \
    yum clean all
RUN yum -y --setopt=tsflags=nodocs install make python2-dciclient \
    python-sphinxcontrib-httpdomain python-sphinx_rtd_theme python-sphinx && \
    yum clean all

ADD dci-doc/python-dciclient python-dciclient

WORKDIR /opt/dci-doc

# By default build the html version of the docs.
CMD ["make", "html"]
