FROM centos:7

LABEL name="DCI API" version="0.0.2"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN yum -y --setopt=tsflags=nodocs install epel-release \
    https://packages.distributed-ci.io/dci-release.el7.noarch.rpm \
    centos-release-openstack-mitaka && \
    yum clean all
RUN yum -y --setopt=tsflags=nodocs install dci-api && \
    yum clean all

WORKDIR /opt/dci-control-server
ENV PYTHONPATH /opt/dci-control-server
ENV DCI_SETTINGS_FILE /tmp/settings/settings.py

EXPOSE 5000

CMD ["python", "/opt/dci-control-server/scripts/runtestserver.py"]
