# DCI DOC
#
# VERSION               0.0.1


FROM centos:7

RUN yum install -y epel-release
RUN yum update -y
RUN yum install -y make git gcc redhat-rpm-config python-devel python-pip
RUN yum clean all

WORKDIR /tmp

ADD dci-doc/requirements.txt requirements.txt
ADD dci-doc/python-dciclient python-dciclient
RUN pip install -r ./requirements.txt

WORKDIR /opt/dci-doc

# By default build the html version of the docs.
ENTRYPOINT "make" "html"
