FROM centos:7

LABEL name="DCI CLIENT" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y install openssh-server; yum clean all; systemctl enable sshd.service
RUN echo root:root | chpasswd && ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -N ''

EXPOSE 22

RUN yum install -y epel-release && yum clean all
RUN yum install -y gcc git libpqxx-devel libffi-devel python-devel python-pip openssl-devel \
    http://packages.distributed-ci.io/dci-release.el7.noarch.rpm && \
    yum clean all

ADD python-dciclient/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

VOLUME ["/usr/lib/python"]

CMD ["/usr/sbin/init"]
