FROM centos:7

LABEL name="DCI WORKER" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

ENV container docker

RUN yum -y --setopt=tsflags=nodocs install epel-release \
    https://packages.distributed-ci.io/dci-release.el7.noarch.rpm \
    centos-release-openstack-ocata && \
    yum -y --setopt=tsflags=nodocs install postfix dci-api openssh-server && \
    yum clean all

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

RUN echo root:root | chpasswd && ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -N ''

RUN systemctl enable postfix dci-worker sshd

EXPOSE 22 5557

CMD ["/usr/sbin/init"]
