# DCI InfluxDB
#
# VERSION               0.0.1


FROM centos:7

RUN yum update -y
RUN yum install -y https://s3.amazonaws.com/influxdb/influxdb-0.11.0-1.x86_64.rpm
RUN yum clean all

USER influxdb

EXPOSE 8083
EXPOSE 8086

CMD ["sh", "-c", "/usr/bin/influxd -config /etc/influxdb/influxdb.conf \
     >>/dev/null 3>>/var/log/influxdb/influxd.log"]
