FROM centos:7

LABEL name="DCI TOX" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN yum install -y epel-release && yum clean all
RUN yum install -y gcc libpqxx-devel libffi-devel \
    python-devel python-tox git python3-devel redhat-rpm-config \
    python-lxml libxslt-devel python-pip python34-setuptools && \
    yum clean all

RUN easy_install-3.4 -U pip

ENV LANG "en_US.UTF-8"
ENV DISABLE_DB_START 1
ENV DISABLE_ES_START 1
ENV DISABLE_INFLUXDB_START 1

ENV TOX_TESTENV_PASSENV "DB_PORT ES_PORT INFLUXDB_PORT_8086_TCP"
ENV DCI_SETTINGS_FILE /tmp/settings/settings_test.py

WORKDIR /opt
