FROM centos:7

LABEL name="DCI DB WATCHER" version="0.0.2"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN yum install -y epel-release && \
    yum install -y graphviz \
    https://kojipkgs.fedoraproject.org//packages/postgresql_autodoc/1.41/6.fc24/noarch/postgresql_autodoc-1.41-6.fc24.noarch.rpm && \
    yum clean all

WORKDIR /mnt/

CMD postgresql_autodoc -u dci -d dci --password=dci -h $DB_PORT_5432_TCP_ADDR -t dot && \
    dot dci.dot -Tpng > dci.png && \
    rm -f dci.dot
