# DCI DB
#
# VERSION               0.0.1


FROM centos:7

RUN yum update -y
RUN yum install -y postgresql-server postgresql-contrib postgresql
RUN yum clean all

ENV PGDATA /var/lib/pgsql/data
ENV PASSWORD "dci"

USER postgres

RUN initdb

# Adjust PostgreSQL configuration to allow connection from all remotes
RUN sed -ri \
    "s/#listen_addresses = '.*?'(.*)/listen_addresses = '*'        \1/" \
    "$PGDATA/postgresql.conf"

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN sed -i \
    "87ahost    all             all             0.0.0.0/0               md5" \
    "$PGDATA/pg_hba.conf"


RUN /usr/bin/pg_ctl -w -t 300 start &&\
    psql -c "CREATE USER dci WITH SUPERUSER PASSWORD '${PASSWORD}';" &&\
    createdb -O dci dci

VOLUME ["$PGDATA"]
EXPOSE 5432
CMD ["postgres"]
