# DCI DB
#
# VERSION               0.0.1


FROM centos:7

RUN yum install -y epel-release
RUN yum update -y
RUN yum install -y gcc gcc-c++ libpqxx-devel libffi-devel libxslt-devel \
                   python-devel python-lxml python-pip redhat-rpm-config
RUN yum clean all

ADD dci-control-server/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

WORKDIR /opt/dci-control-server
ENV PYTHONPATH /opt/dci-control-server
ENV DCI_SETTINGS_FILE /tmp/settings/settings.py

EXPOSE 5000
