FROM centos:7

LABEL name="DCI API" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN yum install -y epel-release && yum clean all
RUN yum install -y gcc gcc-c++ libpqxx-devel libffi-devel libxslt-devel \
    python-devel python-lxml python-pip redhat-rpm-config && \
    yum clean all

ADD dci-control-server/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

WORKDIR /opt/dci-control-server
ENV PYTHONPATH /opt/dci-control-server
ENV DCI_SETTINGS_FILE /tmp/settings/settings.py

EXPOSE 5000
