FROM centos:7

LABEL name="DCI DOC" version="0.0.1"
MAINTAINER DCI Team <distributed-ci@redhat.com>

RUN yum install -y epel-release && yum clean all
RUN yum install -y make git gcc redhat-rpm-config python-devel python-pip && \
    yum clean all

WORKDIR /tmp

ADD dci-doc/requirements.txt requirements.txt
ADD dci-doc/python-dciclient python-dciclient
RUN pip install -r ./requirements.txt

WORKDIR /opt/dci-doc

# By default build the html version of the docs.
ENTRYPOINT "make" "html"
