# DCI Grafana
#
# VERSION               0.0.1


FROM fedora:23

RUN echo -e "[grafana]\n" \
    "\rname=grafana\n" \
    "\rbaseurl=https://packagecloud.io/grafana/stable/el/7/\$basearch\n" \
    "\renabled=1\n" \
    "\rgpgcheck=1\n" \
    "\rgpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana\n" \
    "\rsslverify=1\n" \
    "\rsslcacert=/etc/pki/tls/certs/ca-bundle.crt" > /etc/yum.repos.d/grafana.repo

RUN dnf update -y && dnf install -y grafana crudini && dnf clean all

RUN crudini --set /etc/grafana/grafana.ini 'auth.anonymous' enabled true && \
    crudini --set /etc/grafana/grafana.ini 'users' allow_sign_up false

USER grafana
WORKDIR /usr/share/grafana

EXPOSE 3000
CMD ["sh", "-c", "/usr/sbin/grafana-server --config /etc/grafana/grafana.ini \
     cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana"]
